apiVersion: v1 
kind: Pod 
metadata:
  name: secret-datacenter
spec:
  volumes:
  - name: news_secret_volume
    secret:
      secretName: news
  containers:
    - name: secret-container-datacenter
      image: debian:latest
      command:
      - sleep
      - "100000"
      volumeMounts:
        - name: news_secret_volume
          mountPath: /opt/cluster