apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: grafana-deployment-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      name: grafana-app
      labels:
        app: grafana-app
    spec:
      containers:
        - name: garafa
          image: grafana/grafana
          ports:
            - containerPort: 3000