apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nautilus
  name:  httpd-deploy
  labels:
    app: httpd
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image:  httpd:2.4.28
        name:  httpd

---
kind: Service
apiVersion: v1
metadata:
  name: httpd-service
  namespace: nautilus
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008