apiVersion: v1
kind: Pod 
metadata:
  name: webserver
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
    
    - name: sidecar-container
      image: ubuntu:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      command: ["sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]