apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: ssh-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssh-app
  template:
    metadata:
      name: ssh-app
      labels: 
        app: ssh-app
    spec:
      containers:
        - name: ssh-container
          image: gcr.io/kodekloud/centos-ssh-enabled:node
---
apiVersion: v1 
kind: Service 
metadata: 
  name: ssh-service
spec:
  type: NodePort
  selector:
    app: ssh-app
  ports:
  - port:  8080
    targetPort: 8080
    nodePort: 30012
