apiVersion: v1
kind: Pod 
metadata:
  name: time-check
  namespace: devops
spec:
  containers:
    - name: time-check
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do date ; sleep $TIME_FREQ;done >> /opt/data/time/time-check.log"]
      env:
        - name: time-config
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      volumeMounts:
        - name: log-volume
          mountPath: /opt/data/time 
  volumes:
    - name: log-volume
      emptyDir: {}
