apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ic-deploy-nautilus
  labels:
    app: ic-nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-nautilus
  template:
    metadata:
      labels:
        app: ic-nautilus
    spec:
      volumes:
        - name: ic-volume-nautilus
          emptyDir: {}
      initContainers:
        - name: ic-msg-nautilus
          image: ubuntu:latest
          command:
            ["/bin/bash","-c","echo Init Done - Welcome to xFusionCorp Industries > /ic/news"]
          volumeMounts:
            - name: ic-volume-nautilus
              mountPath: /ic

      containers:
        - name: ic-main-nautilus
          image: ubuntu:latest
          command:
            ["/bin/bash","-c","while true; do cat /ic/news; sleep 5; done"]
          volumeMounts:
            - name: ic-volume-nautilus
              mountPath: /ic    

                