apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: front-end
    tier: nginx-dplm
spec:
  selector:
    matchLabels:
      app: front-end
      tier: nginx
  replicas: 3
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: front-end
        tier: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1
          imagePullPolicy: IfNotPresent