apiVersion: v1 
kind: Pod 
metadata:
  name: volume-share-datacenter
spec:
  containers:
    - name: volume-container-datacenter-1
      image: ubuntu:latest
      command: ["sleep","1000000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/blog

    - name: volume-container-datacenter-2
      image: ubuntu:latest
      command: ["sleep","1000000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/apps

  volumes:
    - name: volume-share
      emptyDir: {}

