- name: "zip and copy to all"
  hosts: all
  become: true
  tasks:
    - name: "zip copy to stapps"
      ansible.builtin.archive:
        path: /usr/src/finance/
        dest: /opt/finance/blog.tar.gz
        format: gz
        force_archive: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"