---
- name: unzip and copy to all
  hosts: all
  become: yes
  tasks:
    - name: unzip copy to stapps
      ansible.builtin.unarchive:
        src: /usr/src/dba/xfusion.zip
        dest: /opt/dba/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755