- name: web app with apache
  hosts: all
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.package:
        name: httpd
        state: present
    - name: start and enable httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true 
    
    - name: create file
      ansible.builtin.copy:
        content: "This is a Nautilus sample file, created using Ansible!"
        dest: /var/www/html/index.html

    - name: add content to html 
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "Welcome to xFusionCorp Industries!"
        insertbefore: BOF
        owner: apache
        group: apache
        mode: 0655