- name: Copy text files to Appservers
  hosts: all
  become: true
  tasks:
    - name: Copy /usr/src/finance/index.html to all
      ansible.builtin.copy:
        src: /usr/src/finance/index.html
        dest: /opt/finance

